### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by fclaussen** [EtienneLem/atom-rdio#11]
1. Opened rdio.com
2. Ctrl+p -> rdio: Play

**Atom Version**: 0.205.0
**System**: Microsoft Windows 8.1
**Thrown From**: [Rdio](https://github.com/EtienneLem/atom-rdio) package, v0.5.1

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
  at exports._errnoException (util.js:734:11)
  at Socket._writeGeneric (net.js:668:26)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at runApplescript (C:\Users\Fernando\.atom\packages\Rdio\node_modules\applescript\lib\applescript.js:58:23)
  at Object.execString (C:\Users\Fernando\.atom\packages\Rdio\node_modules\applescript\lib\applescript.js:19:10)
  at C:\Users\Fernando\.atom\packages\Rdio\lib\rdio-desktop.coffee:55:19

```

### Commands

```
     -7:15.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -7:14.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:11.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -6:08.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:38.8.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
  3x -1:36.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:34.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:34.8.0 rdio:play (ul.list-inline.tab-bar.inset-panel)
     -1:08.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:07.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:05.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:05.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:05.2.0 rdio:play (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "twilight"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.10
file-icons, v1.5.7
minimap, v4.9.2
Rdio, v0.5.1
twilight, v0.3.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by joshua** [comment]
Only Mac OS X is supported. atom-rdio uses Applescript to interface with the Rdio application.
